spring:
  datasource:
    password: 970816
    username: root
    url: jdbc:mysql://localhost:3306/nameplatesystem?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    suffix: .html
    prefix:
      classpath:/templates/
    cache: false

server:
  port: 8089

#»’÷æ
#logging:
#  config: src/main/resources/logging.xml
#  level:
#    root: warn
#    com.mp.dao: trace

mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.landa.nameplatesystem.pojo
  global-config:
    db-column-underline: true
    id-type: 0
    refresh-mapper: false
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl